apiVersion: v1
kind: Service
metadata:
  name: task-distributor
  namespace: central-services
spec:
  selector:
    app: central-node # should target the central-node pod
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090