apiVersion: v1
kind: Service
metadata:
  name: c4d-server
  namespace: central-services
spec:
  selector:
    app: central-node
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091