apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: compute-job  # Changed name to reflect it being a job
  namespace: distributed-system
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1  # Keep at least one master replica
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            app: compute-pod
        spec:
          containers:
            - name: pytorch
              image: lilbillybiscuit/compute-engine:latest  # Use your compute-engine image
              imagePullPolicy: IfNotPresent
#              command: ["python", "train.py"]
              ports:
                - name: pytorch
                  containerPort: 8080
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MVCC_HOST
                  value: compute-node-svc # Correct service name for MVCC
                - name: MVCC_PORT
                  value: "8083"
                - name: CHECKPOINT_DIR
                  value: /mnt/checkpoints
              volumeMounts:
                - name: checkpoint-storage
                  mountPath: /mnt/checkpoints
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "1000m"
                limits:
                  memory: "2Gi"
                  cpu: "2000m"
            - name: monitor
              image: lilbillybiscuit/monitor:latest
              imagePullPolicy: IfNotPresent
              ports:
                - name: monitor
                  containerPort: 8081
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumeMounts:
                - name: shared-memory
                  mountPath: /dev/shm
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"

            # Failure agent sidecar
            - name: failure-agent
              image: lilbillybiscuit/failure-agent:latest
              imagePullPolicy: IfNotPresent
              ports:
                - name: failure-agent
                  containerPort: 8082
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: FAILURE_SERVER_URL
                  value: http://failure-server:8092
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"

            - name: test
              image: ubuntu:22.04
              imagePullPolicy: IfNotPresent
              command: [ "tail", "-f", "/dev/null" ]
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: FAILURE_SERVER_URL
                  value: http://failure-server:8092
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace

          volumes:
            - name: shared-memory
              emptyDir:
                medium: Memory
            - name: checkpoint-storage
              persistentVolumeClaim:
                claimName: checkpoint-pvc
    Worker:
      replicas: 2  # Adjust the number of worker replicas as needed
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            app: compute-pod
        spec:
          containers:
            - name: pytorch
              image: lilbillybiscuit/compute-engine:latest # Use your compute-engine image
              imagePullPolicy: IfNotPresent
#              command: ["python", "train.py"]
              ports:
                - name: pytorch
                  containerPort: 8080
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MVCC_HOST
                  value: compute-node-svc # Correct service name for MVCC
                - name: MVCC_PORT
                  value: "8083"
                - name: CHECKPOINT_DIR
                  value: /mnt/checkpoints
              volumeMounts:
                - name: checkpoint-storage
                  mountPath: /mnt/checkpoints
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "1000m"
                limits:
                  memory: "2Gi"
                  cpu: "2000m"

            # Monitoring sidecar
            - name: monitor
              image: lilbillybiscuit/monitor:latest
              imagePullPolicy: IfNotPresent
              ports:
                - name: monitor
                  containerPort: 8081
              env:
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumeMounts:
                - name: shared-memory
                  mountPath: /dev/shm
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"

            # Failure agent sidecar
            - name: failure-agent
              image: lilbillybiscuit/failure-agent:latest
              imagePullPolicy: IfNotPresent
              ports:
                - name: failure-agent
                  containerPort: 8082
              env:
                - name: ROLE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['training.kubeflow.org/job-role']
                - name: TASK_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: FAILURE_SERVER_URL
                  value: http://failure-server:8092
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"


          volumes:
            - name: shared-memory
              emptyDir:
                medium: Memory
            - name: checkpoint-storage
              persistentVolumeClaim:
                claimName: checkpoint-pvc