apiVersion: v1
kind: Service
metadata:
  name: c4d-server
spec:
  selector:
    app: c4d-server
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: central-mvcc
spec:
  selector:
    app: central-mvcc
  clusterIP: None  # headless service for StatefulSet
  ports:
  - port: 8000
    targetPort: 8000