apiVersion: v1
kind: Service
metadata:
  name: c4d-server
  namespace: c4d-system
spec:
  selector:
    app: c4d-server
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: central-mvcc
  namespace: c4d-system
spec:
  selector:
    app: central-mvcc
  clusterIP: None 
  ports:
  - port: 8000
    targetPort: 8000
