apiVersion: apps/v1
kind: Deployment
metadata:
  name: c4d-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c4d-server
  template:
    metadata:
      labels:
        app: c4d-server
    spec:
      containers:
      - name: c4d-server
        image: c4d-server:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: c4d-server
spec:
  selector:
    app: c4d-server
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
