apiVersion: v1
kind: Service
metadata:
  name: compute-node-svc
  namespace: distributed-system
spec:
  selector:
    app: compute-node
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083