apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure-server
  template:
    metadata:
      labels:
        app: failure-server
    spec:
      containers:
      - name: failure-server
        image: failure-server:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: failure-server
spec:
  selector:
    app: failure-server
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
